### PR TITLE
COUCHED - add findkey method

### PR DESCRIPTION
**Pull request by Hiswe**
Hi again,

So I've repaired my mistakes (I think).

Still without `felix-couchdb` being updated, this won't work anyway :(
I was wandering if it's possible to switch to [nano](https://github.com/dscape/nano) which seems to be more actively maintained?

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Switching to nano would work for me :)

wanna do a separate PR for that?

**Comment by Hiswe** [comment]
If you merge this one, I will make another pull request.
Or I can make another commit to this PR with Nano. 
It's up to you.

**Comment by JohnMcLear** [comment]
Merged :)

**Comment by JohnMcLear** [comment]
oh btw, shouldn't we include couch db tests too?

**Comment by Hiswe** [comment]
Yes, it will be better. But I haven't understood how to test :( `node benchmark.js DATABASENAME` is kind of too obscure for me XD 
Where do I pass all the config necessary for my couch base: host, port, adminName, password ?

**Comment by JohnMcLear** [comment]
afaik just into settings.json ?

**Comment by JohnMcLear** [comment]
Into here: https://github.com/Pita/ueberDB/blob/master/defaultTestSettings.js

**Comment by JohnMcLear** [comment]
Also you might wanna update the readme RE findKeys support! :)

**Comment by Hiswe** [comment]
Thank you! 
I'm working on it.
BTW it could be good to have also a kind of task (makefile, gulp, grunt whatever) to control the coding style. If it has an importance for you :smile:

**Comment by JohnMcLear** [comment]
I prefer gentle hand holding as opposed to enforced linting.  I feel the human touch is often a key part of collaboration.

**Comment by Hiswe** [comment]
I couldn't make the tests pass… at one point or another there is an ECONNRESET :disappointed: Last time it was after *rows: 88000*
BTW, I really don't understand what is the use of doing those tests so many times?
And I haven't figured out if the findKeys method is tested?

**Comment by JohnMcLear** [comment]
cc @Pita

**Pull request merged**
