### PR TITLE
COUCH – change from felix to nano

### PR DESCRIPTION
**Pull request by Hiswe**
So I've achieved to make the tests.
It seems that the problem was with my system [ulimit](https://github.com/dscape/nano/issues/276#issuecomment-96616125)

Tell me if it's good for you!

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Looks great :)_

**Comment by Hiswe** [comment]
Many thanks for the merge!
I just remembered that I forget to update the README…
After that will you publish it to npm?

**Comment by JohnMcLear** [comment]
Please send through PR w/ README stuff in, thanks :)

**Comment by Hiswe** [comment]
In fact I've made two pull request:

* one with the readme update ([#82](https://github.com/Pita/ueberDB/pull/82))
* one with to solve an issue that I'd created in my refactor ([#83](https://github.com/Pita/ueberDB/pull/83))

**Pull request merged**
