### PR TITLE
Bump postgres version

### PR DESCRIPTION
**Pull request by nanaya**
Needed for at least this combination:

- password authentication
- on node 7.2.1
- with postgresql 9.5
- running freebsd 11.0

The app I'm using this for (etherpad-lite) seems to be functional after the update (that's all the test I did).

### CODE REVIEW

**Comment by jonasfugedi** [comment]
Ah, silly me, I did the same changes just, did not check other pull requests!

**Comment by konradjurk** [comment]
Why is this not merged?

**Comment by gracinet** [comment]
👍 
version 4.3.0 of the pg lib is totally broken for me.
As I did some investigations, here are my findings:

it can't handle the md5 authentication challenge properly (I tracked it down to the fact that the salt is passed as a binary string to the `Client.md5` function, which is not ready to handle that).

This seems to be fixed in version 4.5.5 (also quite old) by [this commit](https://github.com/brianc/node-postgres/commit/6fddc566f09cf6b5919638a6f69c251e20437b75)

and more recently, [this pull request](https://github.com/brianc/node-postgres/pull/1183) fixed back the case where the password is actually utf-8. I don't believe this has been released yet

**Comment by lpagliari** [comment]
@Pita any news on this PR? It looks like people trying to use Etherpad with postgres are having trouble lately... Thanks, man!

**Comment by nanaya** [comment]
Already done through other pull request.

**Comment by gracinet** [comment]
Good to now, thanks, will give it a try

**Comment by lpagliari** [comment]
Awesome!

**Comment by lpagliari** [comment]
@Pita or @JohnMcLear can we have a new version on npm, so this change is available for Etherpad, please? Thanks!!

**Pull request closed without merging**
