### PR TITLE
Brought in the new Cassandra driver

### PR DESCRIPTION
**Pull request by simong**
This replaces the old Helenus driver and uses the now "official" nodejs driver to talk to Cassandra.

This is not CQL3 compatible just yet. I'd like to submit a separate PR for that body of work (or update the existing PR)

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Should I wait for CQL3 before merging or should I get this into master now for people to play with?

**Comment by simong** [comment]
I'll do CQL3  in a separate PR. This should at least get us back into the same place as we were.

**Comment by simong** [comment]
Thanks @JohnMcLear, will you also pull this version in etherpad or do you want me to send a PR for that?

**Comment by JohnMcLear** [comment]
I will probably do it when I do an "oudated" sweep, if you want to get it in before feel free to send through a PR :)

**Pull request merged**
