### PR TITLE
Using SADD and SREM as well as SET and GET

### PR DESCRIPTION
**Pull request by christianpbrink**
Our redis lib now maintains, for each pad, (1) a set of chat records and (2) a set of rev records.

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Docs?

**Comment by christianpbrink** [comment]
To be clear, you mean comments explaining what's happening?

On Sunday, February 1, 2015, John McLear <notifications@github.com> wrote:

> Docs?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Pita/ueberDB/pull/72#issuecomment-72391048>.
>


-- 
Sent from my iPhone

**Comment by JohnMcLear** [comment]
Ueberdb isn't just used for etherpad so I dunno if this solution is apt.


----- Reply message -----

**Comment by christianpbrink** [comment]
Makes sense. Up to you.

On Sunday, February 1, 2015, John McLear <notifications@github.com> wrote:

> Ueberdb isn't just used for etherpad so I dunno if this solution is apt.
>
>
> ----- Reply message -----
> From: "Christian Brink" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> To: "Pita/ueberDB" <ueberDB@noreply.github.com
> <javascript:_e(%7B%7D,'cvml','ueberDB@noreply.github.com');>>
> Cc: "John McLear" <John@mclear.co
> <javascript:_e(%7B%7D,'cvml','John@mclear.co');>>
> Subject: [ueberDB] Using SADD and SREM as well as SET and GET (#72)
> Date: Mon, Feb 2, 2015 01:59
>
> To be clear, you mean comments explaining what's happening?
>
> On Sunday, February 1, 2015, John McLear <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Docs?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Pita/ueberDB/pull/72#issuecomment-72391048>.
> >
>
>
> --
> Sent from my iPhone
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/Pita/ueberDB/pull/72#issuecomment-72397579>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Pita/ueberDB/pull/72#issuecomment-72397897>.
>


-- 
Sent from my iPhone

**Comment by JohnMcLear** [comment]
Can you explain why this is needed/desirable?

**Comment by christianpbrink** [comment]
Allows the use of SMEMBERS to retrieve all the keys for chat and rev
records associated with a given pad.  Which allowed a massive speedup in an
external app that does reporting on our EL datastore.

**Comment by JohnMcLear** [comment]
Ahhh, rgr that..

Okay well wouldn't it make sense to move this logic to the findKeys functionality and have the optimizations there for all findKeys events if the database is Redis?

**Comment by christianpbrink** [comment]
It seems to me that maintaining the Redis sets needs to be done during
set/remove events.  Otherwise findKeys doesn't have anything to work with.
Am I thinking upside down about this?

**Comment by JohnMcLear** [comment]
You said "Allows the use of SMEMBERS to retrieve all the keys for chat and rev records associated with a given pad."  So they have to be set with that property too?  I'm not that familiar with Redis but surely that's not the case?

**Comment by christianpbrink** [comment]
I'm not sure if this is answering your question, my apologies if not:

Redis' command KEYS filters through the entire list of keys in the database
in search of those matching a given pattern.  It's O(N) in the size of the
database.  Plus it's a blocking command.  Bad practice in all kinds of
ways.  But if all you're not keeping track of your keys using some
auxiliary data structure, you have to run this command every time you want
a list of the keys that satisfy some condition.  This was killing
performance in our reporting tool.  (Getting the list of keys was taking
*way* longer than looking up those keys values!)

Redis has a 'set' data structure (unrelated to the SET command) that
facilitates O(1) retrieval of a set of values.  A common use case is
storing a set of keys that you want to be able to retrieve efficiently.
Command SADD adds a value to a set, SREM removes a value, and SMEMBERS
returns the list of values.

What my changes do is make sure that whenever we use to SET command to
insert a key representing an edit event, we also use SADD to add that key
to a set representing the edit events for its pad.  Likewise with chat
events, and likewise with REM (we use SREM).

This way our external tool can use SMEMBERS, which speeds up reporting
dramatically.

SMEMBERS would also be smart to use in findKeys.  It already is used in
findKeys for other purposes (retrieving a list of all the pads -- as
opposed to a list of all the events for a given pad).  Unfortunately,
findKeys is kind of confusing -- all this *:*:* business means nothing to
me -- so I don't think I'm the person to do it at the moment.

**Comment by christianpbrink** [comment]
Rather, what doesn't make sense to me is `notKey`.  I don't have any idea
what it means / why it's called that, and so monkeying with the code that
touches it seems like a bad idea.

**Comment by JohnMcLear** [comment]
Yea the whole keys / notkey is pretty unclear, I could probably rewrite the docs around that to clear it up..

RE your implementation I'd suggest we have a way that maybe an array if written during database setup and if the key contains a value from within that array (for example a padrev) that ueberdb does the setadd etc. commands?

I'm just trying to think of ways we can implement this without interfering with other applications that use ueberdb but also making it as simple as possible for etherpad deployments?  Open to suggestions tbh!

**Comment by christianpbrink** [comment]
On Thu, Feb 5, 2015 at 9:41 PM, John McLear <notifications@github.com>
wrote:

> Yea the whole keys / notkey is pretty unclear, I could probably rewrite
> the docs around that to clear it up..
>
> RE your implementation I'd suggest we have a way that maybe an array if
> written during database setup and if the key contains a value from within
> that array (for example a padrev) that ueberdb does the setadd etc.
> commands?
>
> I'm just trying to think of ways we can implement this without interfering
> with other applications that use ueberdb but also making it as simple as
> possible for etherpad deployments? Open to suggestions tbh!
>
I'm not sure I see the problem you're hoping to address, and I also don't
think I understand the mechanism you're proposing to solve it.  Sorry to be
dense.  Can you elaborate?

**Comment by JohnMcLear** [comment]
Well at current your solution only helps Etherpad , and ueberdb is used for other applications..  So we'd need a way so all applications can leverage this additional functionality..  Or alternatively, no applications..

**Comment by christianpbrink** [comment]
Ah, I get it.  Can't think about it right now but I see your point and the
direction you proposed makes sense.

**Comment by JohnMcLear** [comment]
@Pita wanna share some thoughts?

**Pull request closed without merging**
